### ISSUE TITLE
Won't generate images?

### ISSUE THREAD

**Issue by Adil3tr** [Kryptortio/SDAtom-WebUi-us#2]
```
Error completing request
Traceback (most recent call last):
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 469, in process_images
    res = process_images_inner(p)
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 526, in process_images_inner
    file.write(processed.infotext(p, 0))
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 322, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 454, in create_infotext
    negative_prompt_text = "\nNegative prompt: " + p.all_negative_prompts[index] if p.all_negative_prompts[index] else ""
IndexError: list index out of range
```

I'm getting this error. What I'm doing is loading an image in the "others" tab, sending it to txt2img, then adding it to the queue. I do this five times and then press "process queue," Then this error happens. Using tampermonkey.

**Comment by Kryptortio** [comment]
Not sure what you mean by 

> "others" tab

Also I'm not sure why you would be sending images to txt2img, did you mean img2img?

The error itself is not an error from my script, looking at it though I think maybe you do not have the latest version of the webui since the 454 line in my processing.py is blank (it's line 455 for me). Don't know if that is related to the issue though.

Let me also note even though I'm not sure what you are trying to do, you will not be able to queue multiple images (you can load one for i2i and/or one for extra and all queue items will use those) as my script does not support storing images in the queue, only "simple" settings (text, numbers etc). The error you get seems to be that something is missing so maybe that could be it.

**Comment by Adil3tr** [comment]
Sorry, I meant the "PNG info" tab. I take past generations I like, put drag them there, and then click "send to txt2img." That doesn't actually send the image, just all of its parameters including the prompt, steps, loads the checkpoint, etc. The idea being that I could take all my good prompts and make a big queue to generate iterations of them. 

I just downloaded the latest build of automatic and I'll try again.

**Comment by Kryptortio** [comment]
Note that I just made an update to the script since they made some changes so make sure you get the latest version of both. 

Also I tried using PNG info with an image and send to test2img and I was able to queue just fine, an identical image was created so maybe you need to manually edit the queue items to say **"seed":"-1"** rather than a specific seed (or change it before clicking add to queue).

**Comment by Adil3tr** [comment]
Yes, I actually make an XY grid of each image's parameters so I want to keep the seed. I'll see if it works for me, this could save me a huge amount of time.

**Comment by Kryptortio** [comment]
Kinda difficult to determine from that message alone, but I just pushed an update that adds a more "verbose" logging option, if you check that a lot more will be shown in the output console. Also the selectors should hopefully be more robust now since I've added some ids to the AUTOMATIC1111 repo. So try updating both again.

**Comment by Kryptortio** [comment]
Closing this for now, since it's old and got no further updates. 

If there is still an issue (with the latest version of script and webui) check out the new [Troubleshooting section](https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting).
