### ISSUE TITLE
Support for more/custom img2img settings

### ISSUE THREAD

**Issue by Stibo** [Kryptortio/SDAtom-WebUi-us#22]
I can't mention enough how great this extension is. Great work!

I started playing around with controlnet (https://github.com/Mikubill/sd-webui-controlnet) and tried to implement it in my queued workflow. Is there any way to implement custom settings (or settings from extensions) to the queue extension data? I know it does not make any sense to implement other extension settings in your extension.

I've already posted this issue to another extensions (config-presets) and their solution was, to add config files in which you can add custom fields/settings that should be included into the saved preset (https://github.com/Zyin055/Config-Presets/issues/31). Maybe there's a way to do something like this in this queue extension?

**Comment by Kryptortio** [comment]
You can add new elements as ["script extensions"](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions). 
Some examples how that could look:
```
conf.t2i.newElem = {sel:"#element_id textarea"}; // Add a text area element with id element_id 
conf.t2i.newElem = {grad:"element_id"}; // Add an element directly through gradio data structure with id element_id 
conf.i2i.newElem = {grad:"element_id"}; // Same as above but for i2i
conf.ext.newElem = {grad:"element_id"}; // Same as above but for extra tab
```
I think this is similar to that example but it's a small script rather than a file to edit. It's also possible to edit the script directly (see the lines after `let conf = {` ). However the controlnet extension is bad at adding element id's so targeting those elements is not stable as they might change often.

> I know it does not make any sense to implement other extension settings in your extension.

There are [some room for this](https://github.com/Kryptortio/SDAtom-WebUi-us/pull/14) but controlnet would take some work ([some more details on that here](https://www.reddit.com/r/StableDiffusion/comments/11boc0j/i_posted_a_couple_of_month_ago_about_a_queue/jhjqk58/?context=3)).

So I will close this issue now as I think what you asked for specifically is covered with the above suggestion.

**Comment by Stibo** [comment]
Thanks, that looks promising. Do you have any tips how to find a gradio element_id of a field that has no html id attribute? I try to find an selector/element_id of the controlnet "enable" checkbox, but I can't find anything sadly.

**Comment by Kryptortio** [comment]
They are the same thing that's what I meant with them being bad at adding id's, so either the extension needs to be fixed or you have to do it like the first example using the automatically generated id's (that change when the gui change) e.g. #component-85 or some more creative solution like `[title="A value that determines the output of random number generator - if you create an image with same parameters and seed as another image, you'll get the same result"] + input` (input next to the item with the correct mousever description).

**Comment by Stibo** [comment]
Ah ok I get it. Then I'll try to find away round this, until they use ids. Thanks!

**Comment by Anan-Saadi** [comment]
Hey @Stibo, did you manage to create a working solution ?

**Comment by Stibo** [comment]
@Anan-Saadi nope, but I think https://github.com/Mikubill/sd-webui-controlnet added some ids in the meantime, that than now easily be used with the code Kryptortio mentioned above. But I'm not sure...
