### ISSUE TITLE
[Not an Issue] Minor fix to failed imports if they contain asuna \(sao\).

### ISSUE THREAD

**Issue by kyle215ps3** [Kryptortio/SDAtom-WebUi-us#45]
So I discovered a unique issue that is not only limited to this extension but also happens on Agent Scheduler,

When you import the text after making changes, importing asuna \(sao\) for example will always fail every time, this is also happening on agent scheduler as well.
To fix this add 6 more \ with 3 more on each one of the \ originally found it like this: asuna \\\\(sao\\\\), when you do this it will import successfully.
I found out when I noticed asuna \\\\\(sao\\\\\) showing up when using asuna \(sao\) after exporting, this applies to every prompt that has this syntax.
![image](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/87888660/4a9d7cb8-01cb-4390-8d6e-bd124d306f72)

The extra backslash disappears on here but it's this!

Another way to fix this and bypass having to change it every time is use Style Variables and use the trigger prompt on a style prompt setup so then you can still use it with normal syntax.

**Comment by Kryptortio** [comment]
Data is stored as [JSON](https://en.wikipedia.org/wiki/JSON) and in JSON \ is an [escape char](https://en.wikipedia.org/wiki/Escape_character) so that's why this happens and you are correct that this is not an issue but simply how the encoding works. The reason it doubles to \\\\\\\\ (same issue typing it here on GitHub, those 4 \ is actually 8 of them) instead of just \\\\ is because it's escaped twice, once when stored in the queue and once when exported.
